name: first
env:
  filename: 'my_file.txt'

# This step 
on:  
  push:
    branches:
      - main

jobs:
  # 
  simple-artifact:
    name: Prints the date in ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create file
        run: |
          touch ${{filename}}
      - name: Upload simple-artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: simple
          path: ./${{filename}}

